dist: trusty

language: go
go: stable

before_install: make test_lint test_fmt
install:
  - go get -t ./...
  - go get github.com/mattn/goveralls
script: make test_codecov
after_success:
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

notifications:
  email: false
cache:
  directories: $GOPATH/pkg
