dist: trusty

language: go
go: stable

env:
  DOCKER_USERNAME: c4dtbot
  DOCKER_IMAGE: c4dt/drynx:latest

install: go get -t ./...
script: make docker
deploy:
  provider: script
  script: >-
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
    docker push $DOCKER_IMAGE
  on:
    branch: travis

notifications:
  email: false
cache:
  directories: $GOPATH/pkg
