language: go
go:
  - 1.x
# TODO: this should be removed when onet and kyber get updated to v3
install:
  - mkdir $GOPATH/src/github.com/dedis
  - cd $GOPATH/src/github.com/dedis
  - git clone https://github.com/dedis/onet.git
  - git clone https://github.com/dedis/kyber.git
  - git clone https://github.com/dedis/cothority.git
  - cd $GOPATH/src/github.com/dedis/onet
  - git checkout 5796104343ef247e2eed58e573f68c566db2136f
  - cd $GOPATH/src/github.com/dedis/kyber
  - git checkout f55fec5463cda138dfc7ff15e4091d12c4ddcbfe
  - cd $GOPATH/src/github.com/dedis/cothority
  - git checkout 8751beb9f9ec3d093e4cd0ef8f18d4876ec0aae3
  - cd $GOPATH/src/github.com/lca1/drynx
  # ------------------------------------------------------------------
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - make test
after_success:
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
notifications:
  email: false
