Simulation = "ServiceDrynx"
Servers = 13
Bf = 2
Suite = "bn256.G1"
Rounds = 1
Bandwidth = 100
Delay = 20
GroupByValues = [1]
TAGS = "vartime"
RunWait = "2h"

Hosts, NbrServers, NbrVNs, NbrDPs, NbrDPsPerServer, Proofs, Ranges, Obfuscation, OperationName, NbrInput, NbrOutput, DiffPEpsilon, DiffPDelta, DiffPSize, DiffPQuanta, DiffPScale, DiffPLimit, DiffPOpti, DPRows, MinData, MaxData, ThresholdGeneral, ThresholdOther, CuttingFactor, NbrRecords, MaxIterations
25, 6, 7, 12, 2, 1, 18, false, "logistic regression", 1, 90, 0.0, 0.0, 0, 0.0, 0.0, 0.0, false, 9, 0, 1, 1.0, 1.0, 0, 50000, 25