Simulation = "ServiceDrynx"
Servers = 13
Bf = 2
Suite = "bn256.G1"
Rounds = 1
Bandwidth = 100
Delay = 20
GroupByValues = [1]
TAGS = "vartime"
RunWait = "2h"

Hosts, NbrServers, NbrVNs, NbrDPs, NbrDPsPerServer, Proofs, Ranges, Obfuscation, OperationName, NbrInput, NbrOutput, DiffPEpsilon, DiffPDelta, DiffPSize, DiffPQuanta, DiffPScale, DiffPLimit, DiffPOpti, DPRows, MinData, MaxData, ThresholdGeneral, ThresholdOther, CuttingFactor
19, 6, 7, 6, 1, 1, 99, false, "variance", 1, 3, 1.0, 15.0, 100, 0.0, 0.0, 45.0, true, 1, 1, 2, 1.0, 0.3, 0
19, 6, 7, 6, 1, 1, 99, false, "variance", 1, 3, 1.0, 15.0, 100, 0.0, 0.0, 45.0, false, 1, 1, 2, 1.0, 0.3, 00
