Simulation = "ServiceDrynx"
Servers = 13
Bf = 2
Suite = "bn256.G1"
Rounds = 1
Bandwidth = 100
Delay = 20
GroupByValues = [1]
TAGS = "vartime"
RunWait = "15m"

Hosts, NbrServers, NbrVNs, NbrDPs, NbrDPsPerServer, Proofs, Ranges, Obfuscation, OperationName, NbrInput, NbrOutput, DiffPEpsilon, DiffPDelta, DiffPSize, DiffPQuanta, DiffPScale, DiffPLimit, DiffPOpti, DPRows, MinData, MaxData, ThresholdGeneral, ThresholdOther
73, 6, 7, 60, 10, 1, 17, false, "frequencyCount", 1, 10, 0.0, 10.0, 1000, 0.0, 1.0, 45.0, true, 1, 1, 2, 1.0, 1.0